# Generated by Django 3.0.5 on 2020-04-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0004_organizationalinformation_office_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='packageimages')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tntapp.Package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
