# Generated by Django 3.0.5 on 2020-04-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0005_auto_20200416_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageImages',
            new_name='PackageImage',
        ),
        migrations.RenameField(
            model_name='packageimage',
            old_name='images',
            new_name='image',
        ),
    ]
