# Generated by Django 3.0.5 on 2020-04-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0008_auto_20200417_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecategory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='image',
            field=models.ImageField(default='', upload_to='categories'),
            preserve_default=False,
        ),
    ]
