# Generated by Django 3.0.5 on 2020-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0009_auto_20200417_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
