# Generated by Django 3.0.5 on 2020-04-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0010_package_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
