# Generated by Django 3.0.5 on 2020-04-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0011_auto_20200417_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tntapp.Package'),
        ),
    ]
