# Generated by Django 3.0.5 on 2020-04-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0008_auto_20200417_1032'),
        ('tntapp', '0012_article_package'),
    ]

    operations = [
    ]
