# Generated by Django 3.0.5 on 2020-04-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0013_merge_20200417_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='package',
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tntapp.Location'),
        ),
    ]
