# Generated by Django 3.0.5 on 2020-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0014_auto_20200417_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='happycustomer',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=5),
        ),
    ]
