# Generated by Django 3.0.5 on 2020-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0015_happycustomer_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to='pages'),
            preserve_default=False,
        ),
    ]
