# Generated by Django 3.0.5 on 2020-04-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0016_auto_20200419_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages'),
        ),
    ]
