# Generated by Django 3.0.5 on 2020-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0017_auto_20200419_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagefeature',
            name='icon',
            field=models.ImageField(default='', upload_to='features'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagefeature',
            name='short_intro',
            field=models.CharField(default='hello', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
